plugins {
    alias libs.plugins.android.application
    alias libs.plugins.kotlin.android
    alias libs.plugins.hilt
    alias libs.plugins.kapt
    alias libs.plugins.ksp
    id 'kotlin-parcelize'
}

def localPropertiesFile = rootProject.file("local.properties")
def localProperties = new Properties()
localProperties.load(new FileInputStream(localPropertiesFile))

android {
    namespace 'com.insecureshop'
    compileSdkVersion 35

    defaultConfig {
        applicationId "com.insecureshop"
        minSdkVersion 23
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"

        // Should be stored on the server side,
        // left here only for educational purposes
        buildFeatures.buildConfig = true
        buildConfigField 'String', 'USERNAME', localProperties['username']
        buildConfigField 'String', 'PASSWORD', localProperties['password']

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        create("release") {
            keyAlias = localProperties['signingKeyAlias']
            keyPassword = localProperties['signingPassword']
            storeFile = file("insecure_shop")
            storePassword = localProperties['signingPassword']
        }
    }

    dataBinding {
        enabled true
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig = signingConfigs.getByName("release")
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation libs.androidx.appcompat
    implementation libs.androidx.core.ktx
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.webkit

    implementation libs.hilt

    implementation libs.gson

    implementation libs.uploadservice

    implementation libs.material

    implementation libs.glide

    ksp libs.hilt.compiler
    ksp libs.glide.compiler
}
